services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - iot-events-api
      - my-react-app
    networks:
      - my-network

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: db_tac
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - my-network

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/db_tac
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      - postgres
    networks:
      - my-network

  iot-events-api:
    build: ./iot-events-api
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - my-network

  my-react-app:
    build: ./my-react-app
    ports:
      - "3001:3000"
    networks:
      - my-network

  gitlab:
    image: gitlab/gitlab-ee:latest
    hostname: gitlab.example.com
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost:8929'
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "smtp.gmail.com"
        gitlab_rails['smtp_port'] = 587
        gitlab_rails['smtp_user_name'] = "arturs.2019@alunos.utfpr.edu.br"
        gitlab_rails['smtp_password'] = "atrfyj42"
        gitlab_rails['smtp_domain'] = "smtp.gmail.com"
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_tls'] = false
        gitlab_rails['gitlab_email_from'] = 'arturs.2019@alunos.utfpr.edu.br'
        gitlab_rails['gitlab_email_reply_to'] = 'arturs.2019@alunos.utfpr.edu.br'
    ports:
      - "8929:80"
      - "2224:22"
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
    networks:
      - my-network

volumes:
  pgdata:
  gitlab-config:
  gitlab-logs:
  gitlab-data:

networks:
  my-network:
    driver: bridge
